language: java

jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.gpg.skip=true

script:
  - mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.gpg.skip=true
